services:
  db:
    image: postgres:latest
    container_name:  ged-db
    ports: 
    - "${DB_PORT}:5432"
    env_file:
      - .env
    networks:
      - ged-network
  server:
    build: .
    container_name: ged-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ged-network
networks:
  ged-network:
    external: true
    name: ged-network